server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost

logging:
    level:
      org.springframework.data.redis: DEBUG

aws:
  s3:
    bucket-name: your-bucket-name
    region: your-region
    access-key: your-access-key
    secret-key: your-secret-key
